export const COLORS = {
  BRAND_PRIMARY: '#FF4D4F',
  BRAND_SECONDARY: '#FFA940',
  BACKGROUND_LIGHT: '#FFFFFF',
  BACKGROUND_DARK: '#1F1F1F',
  TEXT_DARK: '#262626',
  TEXT_LIGHT: '#F5F5F5',
  BORDER: '#E0E0E0',
  SUCCESS: '#52C41A',
  WARNING: '#FAAD14',
  ERROR: '#FF4D4F',
} as const;

